### ISSUE TITLE
工钱即便没有课也比nicehash的少

### ISSUE THREAD

**Issue by IBAS0742** [ntminer/NtMiner#102]
![image](https://user-images.githubusercontent.com/19849088/110287712-eb9ad100-8021-11eb-8592-4af95091d126.png)
![image](https://user-images.githubusercontent.com/19849088/110287804-108f4400-8022-11eb-8612-bf7f30752c14.png)

或者说需要调节什么参数？

**Comment by ntminer** [comment]
比较挖矿软件只能比较本地算力，通过矿池收益是没法比较挖矿软件的，每天的收益都是不同的。
