### ISSUE TITLE
关于多卡分别挖不同的币

### ISSUE THREAD

**Issue by edisonchan** [ntminer/NtMiner#105]
现在有些卡适合挖 eth，有些适合其他币，开源矿工目前好像还不能支持在同一个实例里指定不同的卡挖不同的币，未来是否可以提供相应的支持呢？

**Comment by ntminer** [comment]
这个需求场景不常用，如果两张卡不适合挖同一种币最好能分开插，这个功能1000个人可能只有一两个人用，现在是牛市不太适合折腾，熊市的时候或许会花时间实现。
