### ISSUE TITLE
有什么办法， 可以让A卡 N卡同时显示在列表吗？ 无法直观看到A卡温度，心慌

### ISSUE THREAD

**Issue by Rempage** [ntminer/NtMiner#112]

**Comment by ntminer** [comment]
AN混插的时候现在界面上不显示A卡，因为现在是牛市不适合频繁更新软件打扰矿工，另外这个功能相对麻烦，准备留到漫长的熊市时再支持AN混插的界面显示。

**Comment by Rempage** [comment]
> AN混插的时候现在界面上不显示A卡，因为现在是牛市不适合频繁更新软件打扰矿工，另外这个功能相对麻烦，准备留到漫长的熊市时再支持AN混插的界面显示。

漫长的熊市， 你说的熊得多熊啊。  还是晚点到来吧 ：）
