### ISSUE TITLE
4K分辨率下超频确认弹窗无法显示

### ISSUE THREAD

**Issue by Zexin** [ntminer/NtMiner#126]

**Comment by jingtianyilong** [comment]
画面右下角。可以点击任务栏查看。

**Comment by Zexin** [comment]
![image](https://user-images.githubusercontent.com/14343081/115881634-e89b5900-a486-11eb-85a9-1f99beabb375.png)
任务栏也看不到

> 画面右下角。可以点击任务栏查看。

**Comment by ntminer** [comment]
目前在超分屏下确实有这个问题，调整分辨率能好，我尝试排查过一下子没有解决掉，后续会再次尝试解决

**Comment by jingtianyilong** [comment]
> 目前在超分屏下确实有这个问题，调整分辨率能好，我尝试排查过一下子没有解决掉，后续会再次尝试解决

我目前的解决方法是
- 任务栏中关闭超频窗口。
- 将主窗口向屏幕左上角移动
- 重新打开超频界面，超频窗口将会在屏幕右下角弹出。

个人猜测弹出窗口的位置是相对于原窗口位置的偏移。

**Comment by ntminer** [comment]
在高分屏下超频弹窗确认窗口跑出可视区域外的BUG已修复，为了不打扰矿工挖矿没有递增版本号，可重新下载开源矿工挖矿端或在挖矿端在线升级转到历史版本重新更新最新版本完成升级。
