### ISSUE TITLE
如何卸载

### ISSUE THREAD

**Issue by lc09cn** [ntminer/NtMiner#127]
C:\Users\x\AppData\Local\NTMiner\Daemon
C:\Users\x\AppData\Local\NTMiner\NoDevFee
这个删除了，如图病毒一样又会自动生成
怎么彻底删除NTminer相关内容？

**Comment by ntminer** [comment]
这是开源矿工.exe运行时释放出来的，无法删除，如果你懂代码你可以改了自用，这是开源矿工群控等功能集的组成部分不能去掉
