### ISSUE TITLE
NTMinerNoDevFee导致SMB传输速度变慢

### ISSUE THREAD

**Issue by wpyyzy** [ntminer/NtMiner#131]
电脑上运行开源矿工的时候，用ipad从电脑上拷贝文件，速度只有1M到2M，但是强行关闭NTMinerNoDevFee.exe这个进程后，拷贝速度能到20M，但是过一会NTMinerNoDevFee.exe又自动启动了，速度又降到1M左右。
有没有办法降低NTMinerNoDevFee对SMB传输速度的影响，或者能手动关闭NTMinerNoDevFee一段时间？

**Comment by ntminer** [comment]
避开Claymore和PhoenixMiner内核就好了，只要不用这两个内核就没有影响了。

**Comment by ThunderEX** [comment]
@ntminer 我看了一下WinDivert有报过类似问题：https://github.com/basil00/Divert/issues/52#issuecomment-491264784
或许可以考虑把WinDivert的filter写得更详细一点，目前是：
`string filter = $"outbound && ip && ip.DstAddr != 127.0.0.1 && tcp && tcp.PayloadLength > 100";`
矿池地址和端口也可以加进去，这样filter过来需要NoDevFee处理的包就会少很多，性能或许有提高。

**Comment by ntminer** [comment]
应该问题是老外内核作者的抽水矿池不一定是用的矿工选择的矿池，所以矿池地址和端口号是假定不知道的。你可以根据需求改改代码重新编译只要重新分发就没有什么问题

**Comment by ntminer** [comment]
有个问题是老外内核作者的抽水矿池不一定是用的矿工选择的矿池，所以矿池地址和端口号是假定不知道的。你可以根据需求改改代码重新编译只要不重新分发就没有什么问题
