### ISSUE TITLE
A卡590，开了计算模式，算力只有24，之前轻松矿工，超频参数一样，可以达到32

### ISSUE THREAD

**Issue by chouxiang99** [ntminer/NtMiner#164]
同样的配置   在轻松矿工上，可以达到32，但是轻松矿工快不行了 所以我换成了这个软件   没想到算力差了那么多   难道a卡在开源矿工上需要什么特殊的设置我没有找到嘛   希望开发能帮忙排查一下问题在哪

**Comment by wangyunqing198801** [comment]
不会超频怪软件

**Comment by chouxiang99** [comment]
> 不会超频怪软件

你有这张卡嘛？你用这张卡超频过嘛？张口就来的？群里那么多人都说a卡的超频不行，算力有差距，到你这就可以了？真能

**Comment by chouxiang99** [comment]
> 不会超频怪软件

还有，不能解决问题，就别在这说这说那的   又没问你，跟着什么一样上来就咬？
