### ISSUE TITLE
实现自选币种、矿池的功能

### ISSUE THREAD

**Issue by ntminer** [ntminer/NtMiner#43]
因为币种和矿池越来越多，人类处理超过7项的信息时存在障碍，所以有必要对信息做下整理。类似交易所那样，矿池和币种后面加个星，点击表示自选再点击表示取消自选，自选的默认出现在自选列表中，默认展示自选列表。

**Comment by suyaofan** [comment]
没代码啊

**Comment by ntminer** [comment]
> 没代码啊

开源矿工所有的代码都是开源的，github上就是代码啊

**Comment by suyaofan** [comment]
你这  没有啊  找了半天都是一些文档 没看见有软件的源代码




------------------ 原始邮件 ------------------
发件人: "ntminer"<notifications@github.com>;
发送时间: 2019年9月23日(星期一) 晚上11:56
收件人: "ntminer/ntminer"<ntminer@noreply.github.com>;
抄送: "、首席执行官_"<549292816@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ntminer/ntminer] 实现自选币种、矿池的功能 (#43)



 
没代码啊
  
开源矿工所有的代码都是开源的，github上就是代码啊
