### ISSUE TITLE
门罗卡对应的xmrig默认抽水5%

### ISSUE THREAD

**Issue by alterhu2020** [ntminer/NtMiner#68]
默认配置发现抽水5%，设置config.json也最低只能到达1%的抽水。建议重新编译源码。

![image](https://user-images.githubusercontent.com/5029046/86992199-8ca36480-c1d3-11ea-859d-7d2c6e5ecbe2.png)

**Comment by ntminer** [comment]
开源矿工一个月后（8月份）下线门罗，请知晓：
由于门罗使用工作和办公的设备挖矿给挖矿行业带来了持久的负面影响，由于开源矿工支持挖门罗导致进入了工作和生活环境，一年来开源多次被人举报可能和此有关。所以为了更好的服务显卡矿工决定1个月后下线门罗，给您带来的不便请见谅。
门罗不符合挖矿原则：https://zhuanlan.zhihu.com/p/150022959
