### ISSUE TITLE
VEGA56用户-在打开客户端以后未工作状态下核心和显存频率全部跑满，实际没有负载

### ISSUE THREAD

**Issue by xxkknn** [ntminer/NtMiner#80]
即打开客户端未开始挖矿的时候，核心频率和显存频率已经跑的最高了，而且此时显卡负载没有提高，发热亦如空载没有增加；
发现此问题是因为听见显卡发出高频工作时特有的轻微啸叫
显卡：vega56
操作系统：WIN10-2004
客户端版本：2.8.5.0
Packages：PhoenixMiner5.4c

**Comment by ntminer** [comment]
如果进行过超频，显卡将一直处于超频状态，不管有没有在工作，超频后可以手动点击那个恢复默认的按钮恢复默认状态，或者重启电脑也会恢复默认状态。

**Comment by xxkknn** [comment]
感谢解答！
我没有通过矿工客户端超频，而是在驱动里调节了电压和频率，确切的说是降压超频了，这么做是为了兼得性能与可靠性；手动点恢复默认之后直接清空了超频设置，这个总体感觉有点···怪
