### ISSUE TITLE
备用矿池没有生效？

### ISSUE THREAD

**Issue by liberize** [ntminer/NtMiner#83]
我看 phoenixminer 的启动参数 -pool2 参数填的是 {pool1}，不是备用矿池的地址

**Comment by ntminer** [comment]
> 我看 phoenixminer 的启动参数 -pool2 参数填的是 {pool1}，不是备用矿池的地址
args = args.Replace("{" + NTKeyword.Pool1ParameterName + "}", prms[NTKeyword.Pool1ParameterName]);
多谢反馈问题，已修复，少了一行代码导致，幸运不影响挖矿，不幸导致问题难以发现，再次感谢你发现问题。因为不影响挖矿和避免打扰矿工这次修复不升级版本号了。
