### ISSUE TITLE
Malware ?

### ISSUE THREAD

**Issue by minhhungit** [ntminer/NtMiner#91]
Hi, Avast antivirus says that NtMiner contains malware, is it mistaken ?

![image](https://user-images.githubusercontent.com/2279508/108664001-6c2adf00-7504-11eb-9a31-910c65d915be.png)

**Comment by ntminer** [comment]
关于挖矿软件报毒，下载的“开源矿工.zip”中有个说明文件，说明文件的内容也可在线浏览：https://zhuanlan.zhihu.com/p/349794576

**Comment by minhhungit** [comment]
okay thanks @ntminer that's good to know
