### ISSUE TITLE
你好，软件运行的时候提示这个错误是怎么回事?CUDART error in CudaProgram cu:29 : unknown error (30)

### ISSUE THREAD

**Issue by MervinTao** [ntminer/NtMiner#92]
CUDART error in CudaProgram cu:29 : unknown error (30)
GPU0 initMiner error: unknown error
Fatal error detected Restarting.

**Comment by ntminer** [comment]
CUDA运行时错误，可能是驱动问题，或不是能挖矿的显卡。我的解释不一定正确，这是什么内核？如果用的NBMiner、BMiner内核，因为作者是国人，可以直接去找作者寻求解决方案。
