### ISSUE TITLE
这个软件会关闭防火墙,UAC且内置了远程控制木马

### ISSUE THREAD

**Issue by supzh** [ntminer/NtMiner#93]
如题,太鸡贼了,我挖到第三天Windows Defender 开始提示这个挖矿工具存在Backdoor:Win32/Bladabindi!ml 后门木马, 只要一打开就会执行这个木马而前三天执行挖矿不会执行任何木马,但会关闭UAC,防火墙, 所以这个挖矿软件已经废了,垃圾,我是在github的下载地址跳转到知乎的页面里下载的.不知道是作者植入的还是被人改包了, 总之, 垃圾.

**Comment by ntminer** [comment]
> 如题,太鸡贼了,我挖到第三天Windows Defender 开始提示这个挖矿工具存在Backdoor:Win32/Bladabindi!ml 后门木马, 只要一打开就会执行这个木马而前三天执行挖矿不会执行任何木马,但会关闭UAC,防火墙, 所以这个挖矿软件已经废了,垃圾,我是在github的下载地址跳转到知乎的页面里下载的.不知道是作者植入的还是被人改包了, 总之, 垃圾.

请不要恶意抹黑，开源矿工没有任何一行代码不可见，我没有作恶的意愿，希望你也不要恶意抹黑。新手有不懂的可以去群里问别人，希望不要恶意抹黑。

**Comment by ntminer** [comment]
开源矿工本身不具有任何恶意代码，且开源矿工100%开源没有任何一行代码不开源！且开源矿工运行时不会自动下载任何可执行代码，之所以这样设计就是为了防止被人恶意抹黑，如果你中木马或者病毒了（你和杀毒软件认为的木马或病毒对于挖矿领域来说多数不是木马和病毒）请去找其他挖矿软件或内核作者，开源矿工不接受任何抹黑。

**Comment by liushuchun** [comment]
其实主要是由于挖矿软件很多模块特征估计是被加到病毒库当中了。
