### ISSUE TITLE
NoDevFee进程严重占用网速

### ISSUE THREAD

**Issue by hyyz17200** [ntminer/NtMiner#96]
如题，NoDevFee开启时，日常上网的网速会收到影响。
比如跑满内网千兆文件传输时，正常情况应有900Mbps以上，但NoDevFee存在时会减速到300Mbps，同时任务管理器可见进程的cpu使用较高。
可以理解，反抽水进程是对所有tcp数据包查包拦截的。但如果挖矿电脑是日常使用的话，会有些影响。
能否考虑改善算法，或者添加一个不使用反抽水的选项？

**Comment by ntminer** [comment]
停止挖矿时过滤tcp的逻辑会退出，每10秒钟会检查一下特定名称的挖矿内核的进程是否存在，如果不存在不挖矿了就退出了不影响网络。
BuildEventPath<Per10SecondEvent>("呼吸表示活着", LogEnum.None,
          path: message => {
              NTMinerRegistry.SetNoDevFeeActiveOn(DateTime.Now);
              NoDevFee.NoDevFeeUtil.StartAsync();
          }, typeof(VirtualRoot));
// NoDevFee.NoDevFeeUtil.StartAsync()中开头部分的逻辑
if (!TryGetCommandLine(out Kernel kernel, out string minerName, out string userWallet)) {
      Stop();
      return;
  }

**Comment by hyyz17200** [comment]
感谢回复。
不过我是希望在挖矿过程中，NoDevFee进程不要影响网络性能，或者提供一个选项不要运行它。
可能我的需求比较特别，专用矿机肯定是不需要考虑这个的。我是想把我自己手头日用机器挖起来。
我只是问一下看能不能改善一下。其实对于大部分矿工来说也没什么问题。

**Comment by ntminer** [comment]
你试试重新编译一下代码，让那个StartAsync方法直接返回就行了，因为开源矿工需要有盈利逻辑/商业模式才能持久发展，我没有办法直接去掉NoDevFee，但是你重新编译了自用是可以去掉的。

**Comment by hyyz17200** [comment]
好的，十分感谢！祝好！
