### ISSUE TITLE
NTminerNoDevFee进程cpu占用率持续维持在100附近

### ISSUE THREAD

**Issue by Allenlee521** [ntminer/NtMiner#99]
使用凤凰5.5c内核挖的ETH，挖了半个小时一直这样，不知道是怎么回事，麻烦作者大大解惑

**Comment by ntminer** [comment]
今天遇到一个CPU 100%的，经查是有杀毒软件导致的，关掉杀毒软件或者信任NTMinerNoDevFee问题消失。
